### ISSUE TITLE
PHP Storm: Cannot show HTML source when including css file with CRLF line separator

### ISSUE THREAD

**Issue by hawkidoki** [timo-reymann/intellij-mjml-support#173]
### What happened?

Hello!

First, thanks for this awesome plugin!

I would like to report a bug. Whenever a CSS file with `CRLF` line separator is included in a MJML template, an error is thrown when I click on the "Show HTML" button, with no HTML being displayed.

**Details:**
- I double checked the MJML doc to make sure the markup is correct and allowed
- The CSS rules are correctly parsed in the plugin preview tab (red background)
- It's only the "Show HTML" tab that doesn't work
- The MJML template works in standalone MJML App v3.1.0-beta / MJML v4.12.0

**Hotfix:**
- The CSS file must use `LF` line separator (`CR` & `CRLF` throw an error)

**My specs:**
PhpStorm 2023.2.3 (Build #PS-232.10072.32, built on October 13, 2023) on Windows 10.

**My MJML Template:**
```xml
<mjml>
    <mj-head>
        <mj-include path="./test.css" type="css" />
    </mj-head>
    
    <mj-body>

        <mj-section>
            <mj-column>
                <mj-text css-class="test">Hello world</mj-text>
            </mj-column>
        </mj-section>

    </mj-body>
</mjml>
```

**My test.css content:**
```css
.test{
  background:#ff0000;
}
```

**PHP Storm Screenshot:**
![Base-519](https://github.com/timo-reymann/intellij-mjml-support/assets/5537083/04666e2b-4dff-4949-977a-deb3e6d01c53)

**PHP Storm Error when clicking "Show HTML":**
```
java.lang.AssertionError: Wrong line separators: '...tar:hover{\r\n    back...' at offset 2158
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2484)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:706)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:124)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:119)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:110)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:129)
	at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.createSourceViewer(MjmlPreviewFileEditor.kt:292)
	at de.timo_reymann.mjml_support.editor.ui.MjmlSplitEditor$createViewActionGroup$4.setSelected(MjmlSplitEditor.kt:127)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:48)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

Thanks and keep up the great work!

### OS

Windows

### What IDE are you facing the problem in?

PhpStorm

### Problem description

See above

### Expected behaviour

See above

### Actual  behaviour

See above

### Steps to Reproduce

See above

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by timo-reymann** [comment]
Heya hwk,
thanks for reporting.

I never saw this issue tbh, but see its very inconvenient on Windows with this combination.

Will work on converting line endings for HTML preview :)

Cheers
Timo

**Comment by timo-reymann** [comment]
Should be fixed in https://github.com/timo-reymann/intellij-mjml-support/commit/c829c849133ee994997b62ef70da7ffadaebd577, and will be shipped with 3.1.1

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2023.11.06-883</a>

**Comment by hawkidoki** [comment]
Hey Timo!

Thanks for the quick update.
I just tested the latest 3.1.1 version, and the issue is still there, sorry.

- `CRLF` & `CR` on css file still throw an error on "Show HTML"
- `LF` on css file still fix the issue

Note that I use PHPStorm `Line Separator` feature (bottom right corner) to switch it. I also tried to switch with Notepad++, same result.
![Base-521](https://github.com/timo-reymann/intellij-mjml-support/assets/5537083/3e3a4864-8483-4631-a407-23ecfce60209)

**test.mjml**
```xml
<mjml>
    <mj-head>
        <mj-include path="./test.css" type="css" />
    </mj-head>
    
    <mj-body>

        <mj-section>
            <mj-column>
                <mj-text css-class="test">Hello world</mj-text>
            </mj-column>
        </mj-section>

    </mj-body>
</mjml>
```

**test.css**
```css
.test{
  background:#ff0000;
}
```

**error**
```
java.lang.AssertionError: Wrong line separators: '...    .test{\r\n    back...' at offset 1847
	at com.intellij.openapi.util.text.StringUtil.assertValidSeparators(StringUtil.java:2484)
	at com.intellij.openapi.editor.impl.DocumentImpl.assertValidSeparators(DocumentImpl.java:706)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:124)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:119)
	at com.intellij.openapi.editor.impl.DocumentImpl.<init>(DocumentImpl.java:110)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createDocument(EditorFactoryImpl.java:129)
	at de.timo_reymann.mjml_support.editor.ui.MjmlPreviewFileEditor.createSourceViewer(MjmlPreviewFileEditor.kt:292)
	at de.timo_reymann.mjml_support.editor.ui.MjmlSplitEditor$createViewActionGroup$4.setSelected(MjmlSplitEditor.kt:127)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:48)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:206)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:520)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by timo-reymann** [comment]
Ok damn it, will have another look :D

**Comment by timo-reymann** [comment]
Alrighty, that was due to escaping the newline characters ... dumb error, fixed now and tagged as 3.1.2.

**Comment by timo-reymann** [comment]
[NEW SNAPSHOT]
Latest snapshot mentioning this issue has been published to marketplace:
    <a href="https://plugins.jetbrains.com/plugin/16418-mjml-support/versions/snapshot">2023.11.07-892</a>

**Comment by timo-reymann** [comment]
New version should be available, can you verufy it works for you? :)

**Comment by hawkidoki** [comment]
Hey Timo!

I just tested the latest 3.1.2 version and I can confirm the issue is now fixed. Yay!

Thanks again for the swift answer & update.

Keep up the great work!
Regards.

**Comment by timo-reymann** [comment]
You are welcome, thanks for your help! :) 

Happy coding
